spring:
  kafka:
    producer:
      bootstrap-servers: "127:0:0:1:9092"
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      group-id: "group_id"


topic:
  name:
    consumer: "test-topic"

auto:
  create:
    topics:
      enable: true

logging:
  level:
    ROOT: info

spring.kafka.consumer.bootstrap-servers: localhost:9092
spring.kafka.consumer.group-id: group-id
spring.kafka.consumer.auto-offset-reset: earliest
spring.kafka.consumer.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.bootstrap-servers: localhost:9092
spring.kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer: org.apache.kafka.common.serialization.StringSerializer
springdoc.swagger-ui.disable-swagger-default-url: true
springdoc.swagger-ui.path: /swagger-ui.html
pringdoc.api-docs.path: /api-docs




